# Generated by Django 4.2.4 on 2023-08-23 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='departments',
            new_name='department',
        ),
    ]
