# Generated by Django 4.2.4 on 2023-08-24 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0005_course_department_remove_userprofile_materials_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
