# Generated by Django 4.2.4 on 2023-08-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.AddField(
            model_name='department',
            name='courses',
            field=models.ManyToManyField(to='storeapp.course'),
        ),
    ]
