# Generated by Django 4.2.4 on 2023-08-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_remove_course_department_department_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='departments',
            field=models.ManyToManyField(related_name='courses', to='storeapp.department'),
        ),
    ]
