# Generated by Django 4.2.4 on 2023-08-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_remove_department_courses_course_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='departments',
            field=models.ManyToManyField(blank=True, to='storeapp.department'),
        ),
    ]
