# Generated by Django 4.2.4 on 2023-08-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0004_alter_course_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='departments',
            field=models.ManyToManyField(related_name='courses', to='storeapp.department'),
        ),
    ]
