# Generated by Django 4.2.4 on 2023-08-23 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0005_alter_course_departments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
